"""empty message

Revision ID: 2408feb0f75f
Revises: a6ebd63b0099
Create Date: 2023-03-21 23:43:12.327721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2408feb0f75f'
down_revision = 'a6ebd63b0099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reports_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incidents_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vacations_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vacations', ['vacations_id'], ['id'])
        batch_op.create_foreign_key(None, 'reports', ['reports_id'], ['id'])
        batch_op.create_foreign_key(None, 'incidents', ['incidents_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint('incidents_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.drop_constraint('vacations_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vacations_employee_id_fkey', 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('roles_employee_id_fkey', 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('reports_employee_id_fkey', 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('incidents_employee_id_fkey', 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vacations_id')
        batch_op.drop_column('incidents_id')
        batch_op.drop_column('reports_id')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
