"""empty message

Revision ID: 3345a718b562
Revises: 51ea4ad75a7d
Create Date: 2023-03-19 21:23:41.417922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3345a718b562'
down_revision = '51ea4ad75a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('local')
        batch_op.drop_column('incidents')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incidents', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('local', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
