"""empty message

Revision ID: 6231e10bfdc0
Revises: 2408feb0f75f
Create Date: 2023-03-22 00:34:27.357449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6231e10bfdc0'
down_revision = '2408feb0f75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('start',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
