"""empty message

Revision ID: 99cbee982fbc
Revises: f6e64c3b6f8a
Create Date: 2023-03-20 00:05:25.028909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cbee982fbc'
down_revision = 'f6e64c3b6f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'client_id')
    )
    op.create_table('client_reservation',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('reservation_id', 'client_id')
    )
    op.create_table('client_table',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('table_id', 'client_id')
    )
    op.create_table('meal_ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'meal_id')
    )
    op.create_table('order_client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'order_id')
    )
    op.create_table('order_table',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('table_id', 'order_id')
    )
    op.create_table('ordered_meals',
    sa.Column('meals_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meals_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('meals_id', 'order_id')
    )
    op.create_table('table_reservation',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('table_id', 'reservation_id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('table')
        batch_op.drop_column('order')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.alter_column('order',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('table')
        batch_op.drop_column('ordered')
        batch_op.drop_column('client')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('table')
        batch_op.drop_column('client')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('client')
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('table', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ordered', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('table', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('items')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('table', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('table_reservation')
    op.drop_table('ordered_meals')
    op.drop_table('order_table')
    op.drop_table('order_client')
    op.drop_table('meal_ingredient')
    op.drop_table('client_table')
    op.drop_table('client_reservation')
    op.drop_table('client_order')
    # ### end Alembic commands ###
