"""empty message

Revision ID: ea100e6c099d
Revises: 6231e10bfdc0
Create Date: 2023-03-26 10:38:06.503533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea100e6c099d'
down_revision = '6231e10bfdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id', 'inventory_id', 'category_id')
    )
    op.create_table('sub_category_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id', 'inventory_id', 'sub_category_id')
    )
    op.drop_table('sub_categories_rel')
    op.drop_table('categories_rel')
    with op.batch_alter_table('inventory_delivery_rel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_delivery_rel', schema=None) as batch_op:
        batch_op.drop_column('id')

    op.create_table('categories_rel',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], name='categories_rel_categories_id_fkey'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name='categories_rel_inventory_id_fkey'),
    sa.PrimaryKeyConstraint('inventory_id', 'categories_id', name='categories_rel_pkey')
    )
    op.create_table('sub_categories_rel',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_categories_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name='sub_categories_rel_inventory_id_fkey'),
    sa.ForeignKeyConstraint(['sub_categories_id'], ['sub_categories.id'], name='sub_categories_rel_sub_categories_id_fkey'),
    sa.PrimaryKeyConstraint('inventory_id', 'sub_categories_id', name='sub_categories_rel_pkey')
    )
    op.drop_table('sub_category_rel')
    op.drop_table('category_rel')
    # ### end Alembic commands ###
