"""empty message

Revision ID: f6e64c3b6f8a
Revises: 3345a718b562
Create Date: 2023-03-19 21:45:04.152548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e64c3b6f8a'
down_revision = '3345a718b562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_delivery_rel',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('deliveries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deliveries_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('inventory_id', 'deliveries_id')
    )
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('schedule')
        batch_op.drop_column('vacations')
        batch_op.drop_column('check_in_out')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_last_deliver_fkey', type_='foreignkey')
        batch_op.drop_column('last_deliver')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_deliver', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inventory_last_deliver_fkey', 'deliveries', ['last_deliver'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_out', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vacations', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    op.drop_table('inventory_delivery_rel')
    # ### end Alembic commands ###
